# Generated by Django 5.2.8 on 2026-01-05 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='description',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='calendarevent',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='created_by',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.client'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='posts_media/'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], default='instagram', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='post_type',
            field=models.CharField(choices=[('Feed', 'Feed'), ('Story', 'Story'), ('Reels', 'Reels')], default='Feed', max_length=10),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='status',
            field=models.CharField(choices=[('Draft', 'Rascunho'), ('Pending', 'Pendente Aprovação'), ('Scheduled', 'Agendado'), ('Published', 'Publicado')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
