# Generated by Django 5.2.8 on 2025-12-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_socialpostdestination_format_type'),
        ('projects', '0002_client_is_active'),
    ]

    operations = [
    ]
