# Generated by Django 5.2.8 on 2026-01-20 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_mediafolder_mediafile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='social_post',
        ),
        migrations.RemoveField(
            model_name='socialpostdestination',
            name='post',
        ),
        migrations.RemoveField(
            model_name='socialpostdestination',
            name='account',
        ),
        migrations.AddField(
            model_name='task',
            name='approval_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='briefing_files',
            field=models.FileField(blank=True, null=True, upload_to='briefings/', verbose_name='Anexo Briefing'),
        ),
        migrations.AddField(
            model_name='task',
            name='briefing_text',
            field=models.TextField(blank=True, null=True, verbose_name='Briefing Detalhado'),
        ),
        migrations.AddField(
            model_name='task',
            name='caption_content',
            field=models.TextField(blank=True, verbose_name='Legenda do Post'),
        ),
        migrations.AddField(
            model_name='task',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.client'),
        ),
        migrations.AddField(
            model_name='task',
            name='content_type',
            field=models.CharField(blank=True, choices=[('feed', 'Feed / Postagem (Quadrado/Portrait)'), ('story', 'Story (Vertical)'), ('reel_short', 'Reels / TikTok / Shorts'), ('video_long', 'Vídeo Longo (Horizontal)'), ('pin', 'Pinterest Pin (Vertical)')], max_length=20, null=True, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='task',
            name='copy_content',
            field=models.TextField(blank=True, verbose_name='Texto da Arte (Headline)'),
        ),
        migrations.AddField(
            model_name='task',
            name='design_files',
            field=models.FileField(blank=True, null=True, upload_to='designs_source/', verbose_name='Editável (PSD/AI)'),
        ),
        migrations.AddField(
            model_name='task',
            name='feedback_image_annotation',
            field=models.TextField(blank=True, null=True, verbose_name='Rabisco (Base64)'),
        ),
        migrations.AddField(
            model_name='task',
            name='final_art',
            field=models.ImageField(blank=True, null=True, upload_to='designs/', verbose_name='Arte Final / Capa'),
        ),
        migrations.AddField(
            model_name='task',
            name='last_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo Reprova'),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Prevista Publicação'),
        ),
        migrations.AddField(
            model_name='task',
            name='script_content',
            field=models.TextField(blank=True, verbose_name='Roteiro (Vídeo/Carrossel)'),
        ),
        migrations.AddField(
            model_name='task',
            name='social_network',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('x', 'X (Twitter)'), ('pinterest', 'Pinterest'), ('threads', 'Threads')], max_length=20, null=True, verbose_name='Rede Social'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Atual'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Geral'),
        ),
        migrations.AlterField(
            model_name='task',
            name='kanban_type',
            field=models.CharField(choices=[('general', 'Geral'), ('operational', 'Operacional (Social Media)')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'A Fazer'), ('doing', 'Em Andamento'), ('done', 'Concluído'), ('briefing', '1. Briefing'), ('copy', '2. Copywriting'), ('design', '3. Design'), ('review_internal', '4. Aprovação Interna'), ('review_client', '5. Aprovação Cliente'), ('scheduled', '6. Agendado/Finalizado')], default='todo', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título / Tema'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='SocialPost',
        ),
        migrations.DeleteModel(
            name='SocialPostDestination',
        ),
    ]
