# Generated by Django 5.2.8 on 2026-01-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_task_social_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(null=True, verbose_name='Prazo de Entrega'),
        ),
    ]
