# Generated by Django 5.2.8 on 2026-01-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tags'),
        ),
    ]
