# Generated by Django 5.2.8 on 2026-01-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_avatar_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('viewer', 'Visualizador'), ('designer', 'Designer'), ('traffic_manager', 'Gestor de Tráfego'), ('photographer', 'Fotógrafo'), ('social_media', 'Social Media'), ('copywriter', 'Copywriter'), ('client', 'Cliente')], default='viewer', max_length=20, verbose_name='Função'),
        ),
    ]
