# Generated by Django 5.2.8 on 2026-01-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='menu_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='on_trial',
            field=models.BooleanField(default=True, verbose_name='Em período de teste?'),
        ),
        migrations.AddField(
            model_name='agency',
            name='paid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Pago até'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
